// <auto-generated />
using System;
using DamYou.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DamYou.Data.Migrations
{
    [DbContext(typeof(DamYouDbContext))]
    [Migration("20260427213347_AddAiAnalysisTables")]
    partial class AddAiAnalysisTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("DamYou.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIndexed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTaken")
                        .HasDatabaseName("IX_Photos_DateTaken");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("IX_Photos_FileHash");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("WatchedFolderId")
                        .HasDatabaseName("IX_Photos_WatchedFolderId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoColorPalette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ColorsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasDatabaseName("IX_PhotoColorPalette_PhotoId");

                    b.ToTable("PhotoColorPalettes");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoDetectedObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("BoundingBoxHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("BoundingBoxWidth")
                        .HasColumnType("REAL");

                    b.Property<float>("BoundingBoxX")
                        .HasColumnType("REAL");

                    b.Property<float>("BoundingBoxY")
                        .HasColumnType("REAL");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .HasDatabaseName("IX_PhotoDetectedObjects_Label");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_PhotoDetectedObjects_PhotoId");

                    b.ToTable("PhotoDetectedObjects");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Dimensions")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_PhotoEmbeddings_PhotoId");

                    b.HasIndex("PhotoId", "ModelName")
                        .HasDatabaseName("IX_PhotoEmbeddings_PhotoId_ModelName");

                    b.ToTable("PhotoEmbeddings");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoOcrText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("TextEmbedding")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId")
                        .IsUnique()
                        .HasDatabaseName("IX_PhotoOcrText_PhotoId");

                    b.ToTable("PhotoOcrTexts");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PipelineTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PipelineTasks_CreatedAt");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_PipelineTasks_PhotoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PipelineTasks_Status");

                    b.ToTable("PipelineTasks");
                });

            modelBuilder.Entity("DamYou.Data.Entities.WatchedFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("WatchedFolders");
                });

            modelBuilder.Entity("DamYou.Data.Entities.Photo", b =>
                {
                    b.HasOne("DamYou.Data.Entities.WatchedFolder", "WatchedFolder")
                        .WithMany()
                        .HasForeignKey("WatchedFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchedFolder");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoColorPalette", b =>
                {
                    b.HasOne("DamYou.Data.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoDetectedObject", b =>
                {
                    b.HasOne("DamYou.Data.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoEmbedding", b =>
                {
                    b.HasOne("DamYou.Data.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PhotoOcrText", b =>
                {
                    b.HasOne("DamYou.Data.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PipelineTask", b =>
                {
                    b.HasOne("DamYou.Data.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Photo");
                });
#pragma warning restore 612, 618
        }
    }
}
