// <auto-generated />
using System;
using DamYou.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DamYou.Data.Migrations
{
    [DbContext(typeof(DamYouDbContext))]
    [Migration("20260427210636_AddPipelineQueue")]
    partial class AddPipelineQueue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("DamYou.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateIndexed")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTaken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WatchedFolderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DateTaken")
                        .HasDatabaseName("IX_Photos_DateTaken");

                    b.HasIndex("FileHash")
                        .HasDatabaseName("IX_Photos_FileHash");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("WatchedFolderId")
                        .HasDatabaseName("IX_Photos_WatchedFolderId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PipelineTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PhotoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PipelineTasks_CreatedAt");

                    b.HasIndex("PhotoId")
                        .HasDatabaseName("IX_PipelineTasks_PhotoId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PipelineTasks_Status");

                    b.ToTable("PipelineTasks");
                });

            modelBuilder.Entity("DamYou.Data.Entities.WatchedFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("WatchedFolders");
                });

            modelBuilder.Entity("DamYou.Data.Entities.Photo", b =>
                {
                    b.HasOne("DamYou.Data.Entities.WatchedFolder", "WatchedFolder")
                        .WithMany()
                        .HasForeignKey("WatchedFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WatchedFolder");
                });

            modelBuilder.Entity("DamYou.Data.Entities.PipelineTask", b =>
                {
                    b.HasOne("DamYou.Data.Entities.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Photo");
                });
#pragma warning restore 612, 618
        }
    }
}
